# Generated by Django 3.2.3 on 2026-05-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20260326_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('transport', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В пути'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='planned', max_length=16)),
                ('is_public', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='cats.cat')),
            ],
            options={
                'ordering': ('-start_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TravelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('address', models.CharField(blank=True, max_length=160)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='cats.travel')),
            ],
            options={
                'ordering': ('travel', 'order'),
            },
        ),
        migrations.CreateModel(
            name='TravelChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('is_done', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='cats.travel')),
            ],
            options={
                'ordering': ('is_done', 'due_date', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='travelstop',
            constraint=models.UniqueConstraint(fields=('travel', 'order'), name='unique_stop_order_per_travel'),
        ),
        migrations.AddConstraint(
            model_name='travelchecklistitem',
            constraint=models.UniqueConstraint(fields=('travel', 'title'), name='unique_checklist_title_per_travel'),
        ),
    ]
